### ISSUE TITLE
Add syntax highlight to code examples

### ISSUE THREAD

**Issue by ai** [HackyDev/pwa-icons-generator#1]
You can add syntax highlight by adding `js` in the beginning of code block like here

![markdown_code_syntax](https://user-images.githubusercontent.com/19343/162626148-d1d84a63-86b4-4f4b-bf25-9d4dba23db03.jpg)

See an example: https://raw.githubusercontent.com/ai/nanoid/main/README.md

**Comment by HackyDev** [comment]
@ai Hey! Thank you for the tip! Fixed the issue. Have a nice day, good sir!
